version: '2.4'
services:
  bot-sepolia:
    environment:
      - NODE_ENV=sepolia
    image: nft_bot
    build:
      context: .
      dockerfile: Dockerfile
    cpus: 1
    mem_limit: 1G
    command: node src/bot.js
    restart: unless-stopped
  bot-polygon:
    environment:
      - NODE_ENV=polygon
    image: nft_bot
    cpus: 1
    mem_limit: 1G
    command: node src/bot.js
    restart: unless-stopped
  bot-arbitrum:
    environment:
      - NODE_ENV=arbitrum
    image: nft_bot
    cpus: 1
    mem_limit: 1G
    command: node src/bot.js
    restart: unless-stopped
  bot-base:
    environment:
      - NODE_ENV=base
    image: nft_bot
    cpus: 1
    mem_limit: 1G
    command: node src/bot.js
    restart: unless-stopped
  bot-apechain:
    environment:
      - NODE_ENV=apechain
    image: nft_bot
    cpus: 1
    mem_limit: 1G
    command: node src/bot.js
    restart: unless-stopped
